// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEYeyBB6NTkQsI8JYgG_OH9UVE9IdJPRM',
    appId: '1:31563242489:web:5cd02821b21f439b25fb28',
    messagingSenderId: '31563242489',
    projectId: 'amarprotikkha-33ab9',
    authDomain: 'amarprotikkha-33ab9.firebaseapp.com',
    storageBucket: 'amarprotikkha-33ab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhUY0q0WRsbPNnC1txX5qemacFimJPQgY',
    appId: '1:31563242489:ios:1f101e5c47413ade25fb28',
    messagingSenderId: '31563242489',
    projectId: 'amarprotikkha-33ab9',
    storageBucket: 'amarprotikkha-33ab9.firebasestorage.app',
    iosBundleId: 'com.example.amarprotikkha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhUY0q0WRsbPNnC1txX5qemacFimJPQgY',
    appId: '1:31563242489:ios:1f101e5c47413ade25fb28',
    messagingSenderId: '31563242489',
    projectId: 'amarprotikkha-33ab9',
    storageBucket: 'amarprotikkha-33ab9.firebasestorage.app',
    iosBundleId: 'com.example.amarprotikkha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEYeyBB6NTkQsI8JYgG_OH9UVE9IdJPRM',
    appId: '1:31563242489:web:dad49a54ff4ace4d25fb28',
    messagingSenderId: '31563242489',
    projectId: 'amarprotikkha-33ab9',
    authDomain: 'amarprotikkha-33ab9.firebaseapp.com',
    storageBucket: 'amarprotikkha-33ab9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARoIDzEky1LdoAbuU_NXvke6VkZ7Y_wAU',
    appId: '1:31563242489:android:650f83685e2ee23b25fb28',
    messagingSenderId: '31563242489',
    projectId: 'amarprotikkha-33ab9',
    storageBucket: 'amarprotikkha-33ab9.firebasestorage.app',
  );

}